### ISSUE TITLE
Problem with elasticsearch configuration

### ISSUE THREAD

**Issue by henres** [symfony/monolog-bundle#236]
Hello,
Have a strange problem with elasticsearch configuration.
On sf 3.2 and monolog-bundle 3.1.

When I define an elasticsearch handler:
```
monolog:
    handlers:
        elasticsearch:
            type: "elasticsearch"
            elasticsearch:
                host: 'elasticsearch'
                port: '9200'
            index: 'ep_php_logs_dev'
            level: 'debug'
            tags: 'monolog.logger'
            channels: ['!event']
```

I have snc/redis enable for another reason
And I have a nice error : 
```
Attempted to load class "Redis" from the global namespace.
Did you forget a "use" statement?
```

I don't have it if I remove elasticsearch handler.

Try this configuration in two different project. Same result

**Comment by Tobion** [comment]
I don't think we can do anything here without knowing your setup. I don't think the elasticsearch handler uses redis. So why would that be related? If there is a connection is probably more related to https://github.com/snc/SncRedisBundle as you say. Please provide a way to reproduce the issue or add some debugingg info.

**Comment by lyrixx** [comment]
Fixed by https://github.com/symfony/symfony/pull/31535

**Comment by Vovchikus** [comment]
Probably, you forgot to add to composer ruflin/elastica library. Had the same issue
